[package]
name = "bitcoin_wallet_test"
version = "0.1.0"
authors = ["Lucas Soriano del Pino <l.soriano.del.pino@gmail.com>"]
edition = "2018"

[dependencies]
bitcoin-wallet = "1.1"
bitcoin = "0.21"
hex = "0.4"
ureq = { version = "0.11", features = ["json"]}
